version: '3'

services:
  bootcamp_osf:
    image: postgres:alpine
    ports:
      - '5432:5433'
    container_name: 'backend_osf'
    restart: always
    volumes:
      - backend_osf-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  backend_osf-data: